plugin:
	gcc -shared -fPIC -o libmatha.dll plugin_math_a.c
	gcc -shared -fPIC -o libmathb.dll plugin_math_b.c
	gcc -shared -fPIC -o librender.dll plugin_render.c
	gcc -shared -fPIC -o libstr.dll plugin_str.c